IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'BookLibrary')) BEGIN

	CREATE TABLE [dbo].[BookLibrary](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[UserId] [int] NOT NULL,
	 CONSTRAINT [PK_BookLibrary] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

END;

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'BookRecord')) BEGIN

	CREATE TABLE [dbo].[BookRecord](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[Title] [nvarchar](max) NOT NULL,
		[Author] [nvarchar](max) NOT NULL,
		[Quantity] [int] NOT NULL,
		[LibraryId] [int] NOT NULL,
	 CONSTRAINT [PK_BookRecord] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

	ALTER TABLE [dbo].[BookRecord]  WITH CHECK ADD  CONSTRAINT [FK_BookRecord_BookLibrary] FOREIGN KEY([LibraryId])
	REFERENCES [dbo].[BookLibrary] ([Id])
	
	ALTER TABLE [dbo].[BookRecord] CHECK CONSTRAINT [FK_BookRecord_BookLibrary]

END;