IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'CardLibrary')) BEGIN

	CREATE TABLE [dbo].CardLibrary(
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[UserId] [int] NOT NULL,
	 CONSTRAINT [PK_CardLibrary] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

END;



IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'CardRecord')) BEGIN

	CREATE TABLE [dbo].CardRecord(
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[Name] [nvarchar](max) NOT NULL,
		[Category] [nvarchar](max) NOT NULL,
		[Quantity] [int] NOT NULL,
		[LibraryId] [int] NOT NULL,
	 CONSTRAINT [PK_CardRecord] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

	ALTER TABLE [dbo].CardRecord  WITH CHECK ADD  CONSTRAINT [FK_CardRecord_CardLibrary] FOREIGN KEY([LibraryId])
	REFERENCES [dbo].CardLibrary ([Id])
	
	ALTER TABLE [dbo].CardRecord CHECK CONSTRAINT [FK_CardRecord_CardLibrary]

END;