IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'MovieLibrary')) BEGIN

	CREATE TABLE [dbo].[MovieLibrary](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[UserId] [int] NOT NULL,
	 CONSTRAINT [PK_MovieLibrary] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

END;

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'MovieRecord')) BEGIN

	CREATE TABLE [dbo].[MovieRecord](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[Title] [nvarchar](max) NOT NULL,
		[Format] [nvarchar](max) NOT NULL,
		[Quantity] [int] NOT NULL,
		[LibraryId] [int] NOT NULL,
	 CONSTRAINT [PK_MovieRecord] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

	ALTER TABLE [dbo].[MovieRecord]  WITH CHECK ADD  CONSTRAINT [FK_MovieRecord_MovieLibrary] FOREIGN KEY([LibraryId])
	REFERENCES [dbo].[MovieLibrary] ([Id])
	
	ALTER TABLE [dbo].[MovieRecord] CHECK CONSTRAINT [FK_MovieRecord_MovieLibrary]

END;