IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'VideogameLibrary')) BEGIN

	CREATE TABLE [dbo].[VideogameLibrary](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[UserId] [int] NOT NULL,
	 CONSTRAINT [PK_VideogameLibrary] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

END;

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'VideogameRecord')) BEGIN

	CREATE TABLE [dbo].[VideogameRecord](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[Title] [nvarchar](max) NOT NULL,
		[Console] [nvarchar](max) NOT NULL,
		[Quantity] [int] NOT NULL,
		[LibraryId] [int] NOT NULL,
	 CONSTRAINT [PK_VideogameRecord] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

	ALTER TABLE [dbo].[VideogameRecord]  WITH CHECK ADD  CONSTRAINT [FK_VideogameRecord_VideogameLibrary] FOREIGN KEY([LibraryId])
	REFERENCES [dbo].[VideogameLibrary] ([Id])
	
	ALTER TABLE [dbo].[VideogameRecord] CHECK CONSTRAINT [FK_VideogameRecord_VideogameLibrary]

END;