IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'BookGenre')) BEGIN

	CREATE TABLE [dbo].BookGenre(
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[GenreName] nvarchar(max) NOT NULL,
	 CONSTRAINT [PK_BookGenre] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].BookRecord
	ADD BookGenreId int
	CONSTRAINT FK_BookGenre
	FOREIGN KEY (BookGenreId) REFERENCES BookGenre(Id);

END;

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'CardType')) BEGIN

	CREATE TABLE [dbo].CardType(
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[TypeName] nvarchar(max) NOT NULL,
	 CONSTRAINT [PK_CardType] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].CardRecord
	ADD CardTypeId int
	CONSTRAINT FK_CardType
	FOREIGN KEY (CardTypeId) REFERENCES CardType(Id);

END;

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'MovieFormat')) BEGIN

	CREATE TABLE [dbo].MovieFormat(
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[FormatName] nvarchar(max) NOT NULL,
	 CONSTRAINT [PK_MovieFormat] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].MovieRecord
	ADD MovieFormatId int
	CONSTRAINT FK_MovieFormat
	FOREIGN KEY (MovieFormatId) REFERENCES MovieFormat(Id);

END;

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'VideogameConsole')) BEGIN

	CREATE TABLE [dbo].VideogameConsole(
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[ConsoleName] nvarchar(max) NOT NULL,
	 CONSTRAINT [PK_VideogameConsole] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].VideogameRecord
	ADD VideogameConsoleId int
	CONSTRAINT FK_VideogameConsole
	FOREIGN KEY (VideogameConsoleId) REFERENCES VideogameConsole(Id);

END;
