
--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [VideogameLibrary] ON

MERGE INTO [VideogameLibrary] AS [Target]
USING (VALUES
  (1,1)
) AS [Source] ([Id],[UserId])
ON ([Target].[Id] = [Source].[Id])
WHEN MATCHED AND (
	NULLIF([Source].[UserId], [Target].[UserId]) IS NOT NULL OR NULLIF([Target].[UserId], [Source].[UserId]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[UserId] = [Source].[UserId]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[UserId])
 VALUES([Source].[Id],[Source].[UserId])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;

DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [VideogameLibrary]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[VideogameLibrary] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO



SET IDENTITY_INSERT [VideogameLibrary] OFF
SET NOCOUNT OFF
GO





--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [VideogameRecord] ON

MERGE INTO [VideogameRecord] AS [Target]
USING (VALUES
  (1,N'Doom',N'PC',5,1)
 ,(2,N'Oblivion',N'PC',3,1)
 ,(3,N'Skyrim',N'Xbox1',7,1)
 ,(4,N'Rust',N'PC',1,1)
 ,(5,N'Fortnite',N'PS4',2,1)
 ,(6,N'Overcooked',N'PC',5,1)
) AS [Source] ([Id],[Title],[Console],[Quantity],[LibraryId])
ON ([Target].[Id] = [Source].[Id])
WHEN MATCHED AND (
	NULLIF([Source].[Title], [Target].[Title]) IS NOT NULL OR NULLIF([Target].[Title], [Source].[Title]) IS NOT NULL OR 
	NULLIF([Source].[Console], [Target].[Console]) IS NOT NULL OR NULLIF([Target].[Console], [Source].[Console]) IS NOT NULL OR 
	NULLIF([Source].[Quantity], [Target].[Quantity]) IS NOT NULL OR NULLIF([Target].[Quantity], [Source].[Quantity]) IS NOT NULL OR 
	NULLIF([Source].[LibraryId], [Target].[LibraryId]) IS NOT NULL OR NULLIF([Target].[LibraryId], [Source].[LibraryId]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[Title] = [Source].[Title], 
  [Target].[Console] = [Source].[Console], 
  [Target].[Quantity] = [Source].[Quantity], 
  [Target].[LibraryId] = [Source].[LibraryId]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[Title],[Console],[Quantity],[LibraryId])
 VALUES([Source].[Id],[Source].[Title],[Source].[Console],[Source].[Quantity],[Source].[LibraryId])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;

DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [VideogameRecord]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[VideogameRecord] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO



SET IDENTITY_INSERT [VideogameRecord] OFF
SET NOCOUNT OFF
GO

